[theme]
primaryColor = "#E63946"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F5F5F5"
textColor = "#1D3557"
font = "sans serif"

[server]
maxUploadSize = 10

[browser]
gatherUsageStats = false
